// export const TREASURY_CANISTER_ID = "";
export const VAULT_CANISTER_ID = import.meta.env.VITE_VAULT_CANISTER_ID;
export const POOL_STATS_CANISTER_ID = import.meta.env.VITE_POOL_STATS_CANISTER_ID;
export const STRATEGY_HISTORY_CANISTER_ID = import.meta.env.VITE_STRATEGY_HISTORY_CANISTER_ID;
